In [37]:
# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
from sklearn.metrics import classification_report, confusion_matrix

In [38]:
df = pd.read_csv("final_dataset1/processed_dataset1.csv")

In [39]:
df

Unnamed: 0 trans_date_trans_time            cc_num  \
0                0   2020-06-21 12:14:25  2291163933867244   
1                1   2020-06-21 12:14:33  3573030041201292   
2                2   2020-06-21 12:14:53  3598215285024754   
3                3   2020-06-21 12:15:15  3591919803438423   
4                4   2020-06-21 12:15:17  3526826139003047   
...            ...                   ...               ...   
555714      555714   2020-12-31 23:59:07    30560609640617   
555715      555715   2020-12-31 23:59:09  3556613125071656   
555716      555716   2020-12-31 23:59:15  6011724471098086   
555717      555717   2020-12-31 23:59:24     4079773899158   
555718      555718   2020-12-31 23:59:34  4170689372027579   

                                    merchant        category     amt    first  \
0                      fraud_Kirlin and Sons   personal_care    2.86     Jeff   
1                       fraud_Sporer-Keebler   personal_care   29.84   Joanne   
2       fraud_Swaniawski, Nitzsche and Welch  health_fitness   41.28   Ashley   
3                          fraud_Haley Group        misc_pos   60.05    Brian   
4                      fraud_Johnston-Casper          travel    3.19   Nathan   
...                                      ...             ...     ...      ...   
555714                 fraud_Reilly and Sons  health_fitness   43.77  Michael   
555715                  fraud_Hoppe-Parisian       kids_pets  111.84     Jose   
555716                       fraud_Rau-Robel       kids_pets   86.88      Ann   
555717                 fraud_Breitenberg LLC          travel    7.99     Eric   
555718                     fraud_Dare-Marvin   entertainment   38.13   Samuel   

            last gender                       street  ...  merch_lat  \
0        Elliott      M            351 Darlene Green  ...  33.986391   
1       Williams      F             3638 Marsh Union  ...  39.450498   
2          Lopez      F         9333 Valentine Point  ...  40.495810   
3       Williams      M  32941 Krystal Mill Apt. 552  ...  28.812398   
4         Massey      M     5783 Evan Roads Apt. 465  ...  44.959148   
...          ...    ...                          ...  ...        ...   
555714     Olson      M          558 Michael Estates  ...  39.946837   
555715   Vasquez      M          572 Davis Mountains  ...  29.661049   
555716    Lawson      F   144 Evans Islands Apt. 683  ...  46.658340   
555717   Preston      M   7020 Doyle Stream Apt. 951  ...  44.470525   
555718      Frey      M     830 Myers Plaza Apt. 384  ...  36.210097   

        merch_long  is_fraud                 Time  Recorded_times  \
0       -81.200714         0  2020-06-21 12:14:25        12:14:25   
1      -109.960431         0  2020-06-21 12:14:33        12:14:33   
2       -74.196111         0  2020-06-21 12:14:53        12:14:53   
3       -80.883061         0  2020-06-21 12:15:15        12:15:15   
4       -85.884734         0  2020-06-21 12:15:17        12:15:17   
...            ...       ...                  ...             ...   
555714  -91.333331         0  2020-12-31 23:59:07        23:59:07   
555715  -96.186633         0  2020-12-31 23:59:09        23:59:09   
555716 -119.715054         0  2020-12-31 23:59:15        23:59:15   
555717 -117.080888         0  2020-12-31 23:59:24        23:59:24   
555718  -97.036372         0  2020-12-31 23:59:34        23:59:34   

        Categorized_times Categorized_trasaction_purpose Birth Year  \
0                       3                              3       1968   
1                       3                              3       1990   
2                       3                              3       1970   
3                       3                              4       1987   
4                       3                              2       1955   
...                   ...                            ...        ...   
555714                  4                              3       1966   
555715                  4   

In [40]:
X = df[['lat', 'long']]
y = df['is_fraud']
X = np.array(X)
X
target_names = ['not fraud', 'fraud']
target_names = np.reshape(target_names, (1,-1))[0]
target_names
print(X)

[[  33.9659  -80.9355]
 [  40.3207 -110.436 ]
 [  40.6729  -73.5365]
 ...
 [  46.1966 -118.9017]
 [  44.6255 -116.4493]
 [  35.6665  -97.4798]]


In [41]:
# Train Test split 
X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                     train_size = 0.7, 
                                     test_size = 0.3, 
                                     random_state = 70)

In [42]:
# Train model
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [43]:
# Predict
y_pred = rf.predict(X_train)
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

[[387493      0]
 [  1397    113]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    387493
           1       1.00      0.07      0.14      1510

    accuracy                           1.00    389003
   macro avg       1.00      0.54      0.57    389003
weighted avg       1.00      1.00      0.99    389003



In [44]:
#evaluation on test data

y_pred = rf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[166081      0]
 [   592     43]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    166081
           1       1.00      0.07      0.13       635

    accuracy                           1.00    166716
   macro avg       1.00      0.53      0.56    166716
weighted avg       1.00      1.00      0.99    166716

