In [1]:
# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
from sklearn.metrics import classification_report, confusion_matrix


In [2]:
df = pd.read_csv("Dataset4/dataset4.csv")

In [3]:
df

step      type      amount     nameOrig  oldbalanceOrg  \
0           1   PAYMENT     9839.64  C1231006815      170136.00   
1           1   PAYMENT     1864.28  C1666544295       21249.00   
2           1  TRANSFER      181.00  C1305486145         181.00   
3           1  CASH_OUT      181.00   C840083671         181.00   
4           1   PAYMENT    11668.14  C2048537720       41554.00   
...       ...       ...         ...          ...            ...   
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0             160296.36  M1979787155            0.00            0.00        0   
1              19384.72  M2044282225            0.00            0.00        0   
2                  0.00   C553264065            0.00            0.00        1   
3                  0.00    C38997010        21182.00            0.00        1   
4              29885.86  M1230701703            0.00            0.00        0   
...                 ...          ...             ...             ...      ...   
6362615            0.00   C776919290            0.00       339682.13        1   
6362616            0.00  C1881841831            0.00            0.00        1   
6362617            0.00  C1365125890        68488.84      6379898.11        1   
6362618            0.00  C2080388513            0.00            0.00        1   
6362619            0.00   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0  

[6362620 rows x 11 columns]

In [4]:
X = df[['amount', 'newbalanceDest']]
y = df['isFraud']
X = np.array(X)
X
target_names = ['not fraud', 'fraud']
target_names = np.reshape(target_names, (1,-1))[0]
target_names
print(X)

[[9.83964000e+03 0.00000000e+00]
 [1.86428000e+03 0.00000000e+00]
 [1.81000000e+02 0.00000000e+00]
 ...
 [6.31140928e+06 6.37989811e+06]
 [8.50002520e+05 0.00000000e+00]
 [8.50002520e+05 7.36010163e+06]]


In [5]:
# Train Test split 
X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                     train_size = 0.7, 
                                     test_size = 0.3, 
                                     random_state = 70)

In [6]:
# Train model
rf = RandomForestClassifier(n_estimators=5, max_depth=10)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=5)

In [7]:
# Predict
y_pred = rf.predict(X_train)
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

[[4447947     102]
 [   4691    1094]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   4448049
           1       0.91      0.19      0.31      5785

    accuracy                           1.00   4453834
   macro avg       0.96      0.59      0.66   4453834
weighted avg       1.00      1.00      1.00   4453834



In [8]:
#evaluation on test data

y_pred = rf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1906302      56]
 [   1925     503]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906358
           1       0.90      0.21      0.34      2428

    accuracy                           1.00   1908786
   macro avg       0.95      0.60      0.67   1908786
weighted avg       1.00      1.00      1.00   1908786

